# Ce modèle AWS SAM a été généré à partir de la configuration de votre fonction.
# Si votre fonction possède un ou plusieurs déclencheurs, notez que les ressources
# AWS associées à ces déclencheurs ne sont pas entièrement spécifiées dans ce
# modèle et qu'elles incluent des valeurs d'espace réservé. Ouvrez ce modèle dans
# AWS Application Composer ou dans votre IDE préféré et modifiez-le pour spécifier
# une application sans serveur avec d'autres ressources AWS.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  llmendpointinvokefunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: ''
      MemorySize: 128
      Timeout: 10
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:eu-west-3:850995548962:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:eu-west-3:850995548962:log-group:/aws/lambda/llm-endpoint-invoke-function:*
            - Effect: Allow
              Action:
                - '*'
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
